/**
 * Verbatim privacy & compliance notice sent as the very first reply to every
 * new user, before any AI processing. Kept as fixed text (not AI-generated) so
 * the disclosure is always complete and accurate.
 *
 * Every claim here must stay true to what the app actually does:
 * - Replies are generated by OpenAI (third-party processor).
 * - Conversation + lightweight profile are stored in Redis, keyed by phone number.
 * - Sessions auto-expire after 30 days of inactivity (SESSION_TTL).
 * - Analytics are anonymous/aggregated; the phone number is SHA-256 hashed there.
 * - "forget me" deletes the session immediately.
 * - Not a medical/crisis service.
 */
module.exports = `🌙 Hi! I'm Luna, an automated AI chatbot from SleepWell+ — here to support you with sleep and stress. A quick note before we start:

• I'm an AI, not a human — and not a doctor or therapist. I offer general support and education, not medical diagnosis or treatment.
• Your messages are sent to a third-party AI provider (OpenAI) to generate replies.
• I remember our chats and a few details (like your age range, sleep concerns, and goals), linked to your phone number, so I can help you better over time.
• Your conversation is automatically deleted after 30 days of inactivity. For improving the service I keep only anonymous, aggregated stats — no message content, and your number is one-way hashed there.
• I don't sell your data or share it for marketing.
• You're in control: text "forget me" anytime to permanently erase everything.
• Under 18? Please use this with a parent or trusted adult's awareness. Under 13? Only with a parent/guardian's permission.
• ⚠️ Not for emergencies. If you're in crisis or thinking about harming yourself, contact 988 (call/text — Suicide & Crisis Lifeline) or text HOME to 741741 right now.

By continuing to chat, you agree to this. Whenever you're ready — what's been going on with your sleep? 💙`;
