/**
 * Verbatim privacy & compliance notice sent as the very first reply to every
 * new user, before any AI processing. Kept as fixed text (not AI-generated) so
 * the disclosure is always complete and accurate.
 *
 * Every claim here must stay true to what the app actually does:
 * - Replies are generated by OpenAI (third-party processor).
 * - Conversation + lightweight profile are stored in Redis, keyed by phone number.
 * - Sessions auto-expire after 30 days of inactivity (SESSION_TTL).
 * - Analytics are anonymous/aggregated; the phone number is SHA-256 hashed there.
 * - "forget me" deletes the session immediately.
 * - Not a medical/crisis service.
 */
module.exports = `🌙 Hey, I'm Luna — an AI sleep & stress buddy from SleepWell+ (not a human or a doctor). Quick heads-up first:

• Your messages are processed by AI (OpenAI) to reply.
• I remember our chats to help you better, auto-delete them after 30 days, and you can text "forget me" anytime to erase everything.
• Not for emergencies — in crisis or thinking of self-harm? Call/text 988, or text HOME to 741741.
• Under 13s should use this with a parent's okay.

By chatting, you're good with this. So… what's been going on with your sleep? 💙

إذا كنت تفضّل أن نكمل بالعربية، فقط ردّ عليّ بالعربية وسأكمل معك بالعربية. 🌙`;
